language: node_js
install:
- npm install -g elm@0.16
cache:
  directories:
  - elm-stuff/packages
  - elm-stuff/build-artifacts
script: bash ./deploy-examples.sh
env:
  global:
    secure: OgKnTSsj8ySNYx0bhXPKxhLuVQ3QeY+FaoN3GH9vx6zQOXnuKl03HihHXIM7qYDsgpEW/WIZqTXUYV0S4LurIZu0JZgJfCPj/xag0NhDEkUv7sUQNfKyq7gQFkjyL6W5Cs/5CBmoECblYSnc9vAC6EXfCKRg19g3hglBAoK7HNFibkm9W0rynzJAn2qRfWQMgpawnmczFDC3eQH7xFabB6R5DFY/H//tIZue+m0r4J+N4EHQonbqa3nGsuN+R/FEXsWr87XXfrJmz6GhHTKYdifGBSuFBOWvpviwXjWtXmgbS+22dmtS3A+lTf8dXoldc26EO3UkADMWopN1QDDua7cv6w1xph86BeoQPz2M5dDO9o1ejqpSPgezpeY26pp64FfpKafHLaTdgoaNe/FkY0hgo/NW8fgGllv5u+K8cHGRhuwe+wnCFhURvBuQM/Cm8I4SmSglvgWysA9nF2k+jwelfwwZ44dgWmzLgk6z+L3OaUk5Jl3irp1dhnNtTD98s5niOBD3RD0yFdEEHHEiDC1DpzKFIZqAsh/pnydhatf17t+64LL2uw0dcvoGGdJblc5jC8A9e4OxYHHX9aE9rSYR/FLYLhz+YYMhgKhdjPF1Bfu4kqCyzK+DRmtHR6Vi8cbsCx4Z57YPfRKkvPEWdaBspHO27hzTf4qzfn1/CdY=
